### ISSUE TITLE
Version discrepancy between repo and npm

### ISSUE THREAD

**Issue by jkesselring-zz** [Talha-T/twitch-wrapper-ts#1]
The package on NPMJS and this repo are different versions. Github appears to be 0.4.1 and NPM reports 0.5.0.

**Comment by Talha-T** [comment]
I probably forgot to push to the Github, I will upload 0.6.0 with API calls and it will be fixed there. Thanks for contacting

**Comment by Talha-T** [comment]
This is fixed now, thanks for letting me know.
