### ISSUE TITLE
parser.parseMessage assumes last colon is the broadcaster:message seperator

### ISSUE THREAD

**Issue by Jondyr** [Talha-T/twitch-wrapper-ts#6]
https://github.com/Talha-T/twitch-wrapper-ts/blob/master/src/parser.ts#L55

line 62: channel and content is seperated by last colon, hence if a message contains a colon the content and channel will be set to incorrect values.

Example message which results in bad behaviour:
`PRIVMSG #twitch-user: http://twitch.tv`

_**actual behaviour:**_
_channel name:_ "#twitch-user: http"
_content:_ "//twitch.tv"
**_expected behaviour:_**
_channel name:_ "#twitch-user" 
_content:_ "http://twitch.tv"

**Comment by NyasakiAT** [comment]
Fixed it in #7

**Comment by Talha-T** [comment]
Nice catch, thanks.

**Comment by Talha-T** [comment]
Fixed with release of 1.0.2
