### ISSUE TITLE
error TS2307: Cannot find module 'twitch-wrapper-ts'.

### ISSUE THREAD

**Issue by aalemayhu** [Talha-T/twitch-wrapper-ts#8]
Hei,

when I try to update our [project][0] to use the latest twitch-wrapper-ts version with the colon fixes. I end up with the error below. Is it possible that I introduced a regression when bumping the dependencies in [Try updating the package dependencies][1]?

Thanks.

```
$ npm update --save
[...]
twitch-wrapper-ts@1.0.2
[...]
$ make build
[...]
ERROR in ./src/twitch/TwitchChat.ts
(1,51): error TS2307: Cannot find module 'twitch-wrapper-ts'.

ERROR in ./src/twitch/TwitchChat.ts
Module not found: Error: Can't resolve 'twitch-wrapper-ts' in '/Users/scanf/src/github.com/scanf/snake/src/twitch'
 @ ./src/twitch/TwitchChat.ts 1:0-43
 @ ./src/states/game.ts
 @ ./src/app.ts
 @ multi ./src/app.ts
[...]
```

[0]: https://github.com/scanf/snake
[1]:  https://github.com/Talha-T/twitch-wrapper-ts/commit/6a2033c83447fe8323e2c833f2f182aebac191f7

**Comment by Talha-T** [comment]
It was an error caused by a silly mistake of mine, try updating it to 1.0.3
